{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Partido 1 (ESP vs CRO)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "DateTableTemplate_2c22ee8a-8634-4df1-b369-d301eb2fb635",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d101a52d-255e-43f5-be2f-5beec2ebfefe",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7d387d82-cd52-4eda-86e6-2dca2c1aef6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b594b871-98d5-4ce6-944b-9aa1e47cd8ff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cb77dcf8-bef5-4657-8594-b22aae76e3df",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ef104bc6-018b-4d1b-a4f5-3277bdeaccf4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "0391bbd0-6496-40c7-8263-ce10d5094cd4",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4066fc53-8196-4fc2-9a83-9e29d59fed75",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "d4b1f25b-d683-4128-816d-c1481c4ba0ea",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "31a11bdb-5910-4341-9320-9db875139c2a",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "a35a9a9d-93f5-498d-b437-7d527c7928aa",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "b81c00cc-ac4a-401a-b723-522cf4603f1a",
                "ordinal": 3
              }
            ],
            "lineageTag": "e1b28743-f983-457d-8b66-d5771f4da443"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "46e21ec3-01a3-4bb4-9bad-d912fde821ee",
        "partitions": [
          {
            "name": "DateTableTemplate_2c22ee8a-8634-4df1-b369-d301eb2fb635",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Partido 1 (ESP vs CRO)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Jugador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0d50ab1-9a40-4799-8d08-51c704dd81c3",
            "sourceColumn": "Jugador",
            "summarizeBy": "none"
          },
          {
            "name": "Minutos jugados",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34ec7447-238e-4966-84c8-43965a5a26ed",
            "sourceColumn": "Minutos jugados",
            "summarizeBy": "sum"
          },
          {
            "name": "Goles",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c50501f-724d-4167-83b5-740e69b05b05",
            "sourceColumn": "Goles",
            "summarizeBy": "sum"
          },
          {
            "name": "Asistencias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb6080e0-1d01-4bd4-b3e6-591442a38819",
            "sourceColumn": "Asistencias",
            "summarizeBy": "sum"
          },
          {
            "name": "Disparos a puerta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c58a455f-91e0-4bf3-be88-4e54e6e8523b",
            "sourceColumn": "Disparos a puerta",
            "summarizeBy": "sum"
          },
          {
            "name": "Disparos fuera",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50748606-d5c0-4a59-aacb-e454e52bc203",
            "sourceColumn": "Disparos fuera",
            "summarizeBy": "sum"
          },
          {
            "name": "Faltas recibidas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06683038-0787-4924-8733-6022b1e5bfa2",
            "sourceColumn": "Faltas recibidas",
            "summarizeBy": "sum"
          },
          {
            "name": "Recuperaciones",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "984b5fd6-0e61-4369-a2a3-e0c271c2677a",
            "sourceColumn": "Recuperaciones",
            "summarizeBy": "sum"
          },
          {
            "name": "Faltas cometidas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d4d94060-a1f5-4cd3-9113-0504dba70390",
            "sourceColumn": "Faltas cometidas",
            "summarizeBy": "sum"
          },
          {
            "name": "Tarjetas amarillas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "031ce1d8-607b-49e0-8d7f-81d64ef39395",
            "sourceColumn": "Tarjetas amarillas",
            "summarizeBy": "sum"
          },
          {
            "name": "Tarjetas rojas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "593be83b-28ad-4ac9-b404-5d079f03cec0",
            "sourceColumn": "Tarjetas rojas",
            "summarizeBy": "sum"
          },
          {
            "name": "Pases completados",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f45ead70-45ff-4c8e-af62-1a512013c0d0",
            "sourceColumn": "Pases completados",
            "summarizeBy": "sum"
          },
          {
            "name": "Total pases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "462727d6-1894-4309-886c-7af67a4a8367",
            "sourceColumn": "Total pases",
            "summarizeBy": "sum"
          },
          {
            "name": "Regates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2c57d0bb-a14d-4be7-8b73-1f5b4666c886",
            "sourceColumn": "Regates",
            "summarizeBy": "sum"
          },
          {
            "name": "Paradas realizadas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "acb1779f-5297-4afd-9d24-dacb1f5d5051",
            "sourceColumn": "Paradas realizadas",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "26fbe534-1072-4781-ab7d-53f7dac2cf4c",
        "measures": [
          {
            "name": "Suma Total Pases",
            "expression": "SUM('Partido 1 (ESP vs CRO)'[Pases completados])",
            "formatString": "0",
            "lineageTag": "2fd173dd-aa38-4223-920a-a1610a26fff0"
          },
          {
            "name": "Pases Fallados",
            "expression": "SUM('Partido 1 (ESP vs CRO)'[Total pases]) - SUM('Partido 1 (ESP vs CRO)'[Pases completados])",
            "formatString": "0",
            "lineageTag": "ae1488fd-bd03-48af-a10d-66e5c2160a4a"
          },
          {
            "name": "Total Faltas",
            "expression": "SUM('Partido 1 (ESP vs CRO)'[Faltas cometidas]) ",
            "formatString": "0",
            "lineageTag": "4c59170d-01d3-440b-ab4b-f5240b98900d"
          },
          {
            "name": "Total Tiros A Puerta",
            "expression": "SUM('Partido 1 (ESP vs CRO)'[Disparos a puerta])",
            "formatString": "0",
            "lineageTag": "1793877b-940e-4b3d-9453-8e9cca928df5"
          },
          {
            "name": "Total Tiros Fuera",
            "expression": "SUM('Partido 1 (ESP vs CRO)'[Disparos fuera])",
            "formatString": "0",
            "lineageTag": "3d57e527-dce1-4b0b-9d0e-03cdaf15bd60"
          },
          {
            "name": "Total Tiros",
            "expression": "SUM('Partido 1 (ESP vs CRO)'[Disparos a puerta]) + SUM('Partido 1 (ESP vs CRO)'[Disparos fuera])",
            "formatString": "0",
            "lineageTag": "ff5b44f1-486e-4cc6-85bd-d269add133c2"
          }
        ],
        "partitions": [
          {
            "name": "Partido 1 (ESP vs CRO)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Users\\msarm\\Desktop\\Power BI\\eurocopa\\Partido 1 (ESP vs CRO).csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}}),",
                "    #\"Filas en blanco eliminadas\" = Table.SelectRows(#\"Tipo cambiado\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Filas en blanco eliminadas\",{{\"Column1\", \"Jugador\"}, {\"Column2\", \"Minutos Jugados\"}, {\"Column3\", \"Goles\"}, {\"Column4\", \"Asistencias\"}, {\"Column5\", \"Disparos a puerta\"}, {\"Column6\", \"Disparos fuera\"}, {\"Column7\", \"Faltas recibidas\"}, {\"Column8\", \"Recuperaciones\"}, {\"Column9\", \"Faltas cometidas\"}, {\"Column10\", \"Tarjetas amarillas\"}, {\"Column11\", \"Tarjetas rojas\"}, {\"Column12\", \"Pases completados\"}, {\"Column13\", \"Total pases\"}, {\"Column14\", \"Regates\"}, {\"Column15\", \"Paradas realizadas\"}}),",
                "    #\"Filas superiores quitadas\" = Table.Skip(#\"Columnas con nombre cambiado\",1),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Filas superiores quitadas\",{{\"Minutos Jugados\", Int64.Type}, {\"Goles\", Int64.Type}, {\"Asistencias\", Int64.Type}, {\"Disparos a puerta\", Int64.Type}, {\"Disparos fuera\", Int64.Type}, {\"Faltas recibidas\", Int64.Type}, {\"Recuperaciones\", Int64.Type}, {\"Faltas cometidas\", Int64.Type}, {\"Tarjetas amarillas\", Int64.Type}, {\"Tarjetas rojas\", Int64.Type}, {\"Pases completados\", Int64.Type}, {\"Total pases\", Int64.Type}, {\"Regates\", Int64.Type}, {\"Paradas realizadas\", Int64.Type}, {\"Jugador\", type text}}),",
                "    #\"Columnas con nombre cambiado1\" = Table.RenameColumns(#\"Tipo cambiado1\",{{\"Minutos Jugados\", \"Minutos jugados\"}})",
                "in",
                "    #\"Columnas con nombre cambiado1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}